### ISSUE TITLE
Crash Joining World

### ISSUE THREAD

**Issue by PopcornHead51** [Gordon-Frohman/Metaworlds-Mixins#7]
Long modlist but I got this crash when joining/creating a world with the mod in my pack:

[crash-2025-05-04_02.02.57-server.txt](https://github.com/user-attachments/files/20026359/crash-2025-05-04_02.02.57-server.txt)

**Comment by Gordon-Frohman** [comment]
Hmm, that's too vague
Can you please provide me your full log?
And the crash happens every time you join a world, am I right?

**Comment by PopcornHead51** [comment]
It happens every time I've tried joining/creating a world, and I tried several times, so it's safe to say every time. Here's the full log

[2025-05-04-1.log](https://github.com/user-attachments/files/20029530/2025-05-04-1.log)

**Comment by Gordon-Frohman** [comment]
It seems that the issue is in chunkapi mod
I'll look further into it

**Comment by Gordon-Frohman** [comment]
Try updating chunkapi to 0.6.2
The issue should be fixed now

**Comment by PopcornHead51** [comment]
I still have a crash when joining/creating a world, albeit, with a different error:

[latest.log](https://github.com/user-attachments/files/20086694/latest.log)

**Comment by Gordon-Frohman** [comment]
Now the problem seems to be in ArchaicFix
Will look into it as well

**Comment by Gordon-Frohman** [comment]
Sorry for taking so long
The ArchaicFix incompatibility is fixed in version 1.1.2
You can download it from here
