### ISSUE TITLE
Crash With Hardcore Ender Expansion

### ISSUE THREAD

**Issue by PopcornHead51** [Gordon-Frohman/Metaworlds-Mixins#8]
The game crashes when creating a subworld with hardcore ender expansion installed. Here's the log:

[prismlog.txt](https://github.com/user-attachments/files/20523637/prismlog.txt)

**Comment by Gordon-Frohman** [comment]
"Well, here we are again
It's always such a pleasure"
(c)GLaDOS
I'll look into it

**Comment by Gordon-Frohman** [comment]
Okay, the hardest part was getting the HEE's source code
Fixed the issue in v1.1.3

**Comment by PopcornHead51** [comment]
I still get a crash on creating a meta-world

[prismlog.txt](https://github.com/user-attachments/files/20530349/prismlog.txt)

**Comment by Gordon-Frohman** [comment]
Now I have pretty much no idea what could be causing it
Are you using a lot of mixin-based mods?

**Comment by Gordon-Frohman** [comment]
It seems to me that some mod (most likely not HEE) is injecting into `EntityPlayerMP` class, making `func_147097_b` private again, despite me setting it to public.
